### ISSUE TITLE
'tensorflow_model_server' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by devgz** [TinusGreen/captcha_cracking#2]
**> 'tensorflow_model_server' is not recognized as an internal or external command,
> operable program or batch file.**

After executing:
> tensorflow_model_server --port=9000 --rest_api_port=9001 --model_name=<yourmodelname> --model_base_path=<full path to exported model directory>

Can you provide the exact parameters you inserted? 

Im using windows 7, how would I go about creating the tensorflow server. 

Please be thorough, I tried installing docker and running codes found from tensorflow site but having hard time decoding it. 

Or can you tell us how you set it up? What OS specs etc.

Thanks you!

**Comment by TinusGreen** [comment]
Your problem is not the parameters, it is that you haven't install the model server. 

The model server is additional software you need to install. I'd highly recommend installing virtualbox and running a clean Ubuntu install for this.

Once installed used the following guide:

https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/setup.md

The installation using APT is the simplest. 

`tensorflow-model-server` can then be invoked from terminal.

**Comment by devgz** [comment]
![docker2](https://user-images.githubusercontent.com/39295947/51502152-c0ea5180-1da2-11e9-88cc-52f5a152c335.PNG)
![dockerproblems](https://user-images.githubusercontent.com/39295947/51502153-c0ea5180-1da2-11e9-96a1-942701d80c05.PNG)


Hello, Im currently following your instructions for the virtual box. 

Can you give me some insight on the docker method? Primarily, what target source to put regarding my machine.
